import 'classnames';
import 'dva';
import 'dva-loading';
import 'gitment';
import 'gitment/style/default.css';
import 'highlight.js';
import 'history';
import 'nprogress';
import 'nprogress/nprogress.css';
import 'path';
import 'react';
import 'react-dom';
import 'react-lazyload';
import 'react-typist';
import 'styled-components'
import 'polished'